version: "3"

services:
  caddy:
    image: "rdisckyzp/go-micro-caddy:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "9000:9000" # expose cadddy for front-end
      - "9001:9001" # expose cadddy for back-end
      - "443:443" # for ssl
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  front-end:
    image: "rdisckyzp/front-end:1.0.1"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      BROKER_URL: "http://backend"

  broker-service:
    image: "rdisckyzp/broker-service:1.0.1"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    image: "rdisckyzp/authentication-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger-service:
    image: "rdisckyzp/logger-service:1.0.1"
    deploy:
      mode: replicated
      replicas: 1

  listener-service:
    image: "rdisckyzp/listener-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1

  mail-service:
    image: "rdisckyzp/mail-service:1.0.0"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MAIL_DOMAIN: localhost
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: test
      MAIL_PASSWORD: test
      MAIL_ENCRYPTION: none
      MAIL_FROM_NAME: test
      MAIL_FROM_ADDRESS: test@localhost.com

  rabbitmq:
    image: "rabbitmq:4.0.5-alpine"
    deploy:
      mode: global

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "8025:8025"
    deploy:
      mode: global

  mongo:
    image: "mongo:8.0-noble"
    ports:
      - "27018:27017"
    deploy:
      mode: global
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo/:/data/db

  postgres:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

volumes:
  caddy_data:
    external: true
  caddy_config:
